fix: Define yes_spread_pct before using it
BUG:
NameError: name 'yes_spread_pct' is not defined at line 545

CAUSE:
In previous commit, I added code to check:
  if yes_spread_pct > 50:
But forgot to calculate yes_spread_pct before using it!

FIX:
Calculate yes_spread_pct right after getting best prices:
  yes_spread = yes_best_ask - yes_best_bid
  temp_yes_mid = (yes_best_bid + yes_best_ask) / 2
  yes_spread_pct = (yes_spread / temp_yes_mid * 100)

Now variable is defined before it's used at line 545.

Related to: variable definition, spread calculation, Python NameError